import { Inter } from "next/font/google";
import "./globals.css";
import Menu from "@/components/Menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DekReza's Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta property="og:title" content="DekReza's Portfolio Page" />
      <meta
        property="og:description"
        content="Hi i am Reza, i do coding custom YT CHAT CSS for Vtuber/Streamer, open for collaboration projects, take a look my portfolis here ✨"
      />
      <meta
        property="og:image"
        content="https://res.cloudinary.com/dxcmt3zoc/image/upload/v1700500680/Group_35_2_wiftx7.png"
      />
      <link rel="icon" href="/favicon.png" />
      <meta property="og:url" content="https://dekreza.site/" />
      <meta
        name="twitter:card"
        content="https://res.cloudinary.com/dxcmt3zoc/image/upload/v1700500680/Group_35_2_wiftx7.png"
      />
      <body className={`${inter.className} relative `}>
        <Menu />
        {children}
      </body>
    </html>
  );
}
